name: PHP Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # update to PHP 8.3 when possible, currently not supported
          php-version: "8.2"
          extensions: mbstring, intl
          coverage: xdebug

      - name: Install Symfony CLI
        run: |
          curl -sS https://get.symfony.com/cli/installer | bash
          mv /home/runner/.symfony5/bin/symfony /usr/local/bin/symfony
          # when testing locally with act use
          # mv /root/.symfony*/bin/symfony /usr/local/bin/symfony

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run linter
        run: composer run-script cs

      - name: Run tests
        run: composer run-script test

      - name: Run PHPStan
        run: composer run-script phpstan

      - name: Run security check
        run: symfony security:check
